- hosts: localhost
  become: true
  gather_facts: yes
  vars_files:
    - ./ansible-vars.yaml

  pre_tasks:
  - name: Install update-manager-core
    apt: name=update-manager-core

  - name: Update apt repo and cache
    apt:
      update_cache: yes
      force_apt_get: yes
      cache_valid_time: 3600

  - name: Upgrade all packages on servers
    apt:
      upgrade: dist
      force_apt_get: yes

  - name: Add PPA repositories
    ansible.builtin.apt_repository:
      repo: "{{ item }}"
    with_items:
    - ppa:neovim-ppa/stable
    - ppa:cwchien/gradle

  - name: Install node ppa
    shell: curl -sL https://deb.nodesource.com/setup_current.x | sudo -E sh -

  - name: Install packages
    apt:
      name: "{{ item }}"
      state: latest
    with_items:
    - apt-transport-https
    - black
    - cargo
    - cpanminus
    - daemonize
    - dbus-user-session
    - default-jdk
    - dos2unix
    - fd-find
    - flake8
    - fontconfig
    - fzf
    - gcc
    - gradle
    - g++
    - jq
    - locate
    - luarocks
    - lynx
    - make
    - neovim
    - nodejs
    - python3-dev
    - python3-pip
    - ripgrep
    - ruby-full
    - shellcheck
    - silversearcher-ag
    - sqlite3
    - tmux
    - zsh

  - name: Install python packages
    pip:
      name: "{{ item }}"
      extra_args: --upgrade
      executable: pip3
    with_items:
    - pynvim
    - msgpack

  - name: Install NPM packages
    community.general.npm:
      name: "{{ item }}"
      version: latest
      global: yes
    with_items:
    - npm
    - neovim
    - '@fsouza/prettierd'
    - eslint_d

  - name: Install latest neovim gem
    community.general.gem:
      name: neovim
      state: latest

  - name: Install glow
    community.general.snap:
      name: "{{ item.name }}"
      classic: "{{ item.classic }}"
    when: "{{ item.install }}"
    with_items:
    - { name: glow, classic: no, install: yes }
    - { name: powershell, classic: yes, install: "{{ install_pwsh }}" }

  - name: Install Azure CLI
    shell: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
    when: install_azcli

  - name: Get dive latest version
    shell: |
      DIVE_VERSION=$(curl -s "https://api.github.com/repos/wagoodman/dive/releases/latest" | grep -Po '"tag_name": "v\K[0-9.]+')
      curl -Lo dive.deb "https://github.com/wagoodman/dive/releases/latest/download/dive_${DIVE_VERSION}_linux_amd64.deb"
      sudo apt install -y ./dive.deb
      rm -rf dive.deb

  roles:
  - role: gantsign.golang
    when: install_go
    # vars:
    # - golang_version: {{ golang_version }}
    # - golang_install_dir: /opt/go
  - role: lean_delivery.java
    # vars:
      # transport: repositories
      # java_major_version: "{{ java_major_version }}"
    when: install_java or install_maven
  - role: tecris.maven
    when: install_maven

  post_tasks:
  - name: Install kubectl and kubelogin
    shell: az aks install-cli --install-location /usr/local/bin/kubectl --kubelogin-install-location /usr/local/bin/kubelogin

  - name: Remove useless packages from the cache
    apt:
      autoclean: yes

  - name: Remove dependencies that are no longer required
    apt:
      autoremove: yes
