- hosts: localhost
  become: true
  gather_facts: yes
  vars:
    install_azcli: true
    install_pwsh: true
    install_go: true
    golang_version: 1.18

  pre_tasks:
  # - name: Install roles
  #   command: ansible-galaxy role install {{ item }}
  #   with_items:
  #   - gantsign.golang

  - name: Install update-manager-core
    apt: name=update-manager-core

  - name: Update apt repo and cache
    apt:
      update_cache: yes
      force_apt_get: yes
      cache_valid_time: 3600

  - name: Upgrade all packages on servers
    apt:
      upgrade: dist
      force_apt_get: yes

  - name: Add Neovim stable repository from PPA and install its signing key on Ubuntu target
    ansible.builtin.apt_repository:
      repo: ppa:neovim-ppa/stable

  - name: Install node ppa
    shell: curl -sL https://deb.nodesource.com/setup_current.x | sudo -E sh -

  - name: Install packages
    apt: name={{ item }}
    with_items:
    - apt-transport-https
    - black
    - cargo
    - cpanminus
    - daemonize
    - dbus-user-session
    - default-jdk
    - dos2unix
    - fd-find
    - flake8
    - fontconfig
    - fzf
    - gcc
    - g++
    - locate
    - luarocks
    - lynx
    - make
    - neovim
    - nodejs
    - python3-dev
    - python3-pip
    - ripgrep
    - ruby-full
    - shellcheck
    - silversearcher-ag
    - sqlite3
    - tmux
    - zsh

  - name: Install python packages
    pip:
      name: "{{ item }}"
      extra_args: --upgrade
      executable: pip3
    with_items:
    - pynvim
    - msgpack

  - name: Install NPM packages
    community.general.npm:
      name: "{{ item }}"
      version: latest
      global: yes
    with_items:
    - npm
    - neovim
    - '@fsouza/prettierd'
    - eslint_d

  - name: Install latest neovim gem
    community.general.gem:
      name: neovim
      state: latest

  - name: Install glow
    community.general.snap:
      name: "{{ item }}"
      state: latest
    with_items:
      - glow

  - name: Install powershell
    community.general.snap:
      name: "{{ item }}"
      extra_args: --classic
      state: latest
    when: install_pwsh
    with_items:
      - powershell

  - name: Install Azure CLI
    shell: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

  - name: Install kubectl and kubelogin
    shell: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo -E sh -
    when: install_azcli

  - name: Remove useless packages from the cache
    apt:
      autoclean: yes

  - name: Remove dependencies that are no longer required
    apt:
      autoremove: yes

  roles:
  - role: gantsign.golang
    when: install_go
    vars:
    # - golang_version: {{ golang_version }}
    - golang_install_dir: /usr/local/go

  post_tasks:
