- hosts: localhost
  become: true
  gather_facts: yes
  tasks:
  - name: ensure fonts directory
    file:
      path: "{{ lookup('env', 'HOME') }}/.fonts"
      state: directory

  - name: Caskaydia exists
    shell: "ls {{ lookup('env', 'HOME') }}/.fonts/Caskaydia*Nerd*Font*Complete*"
    register: Caskaydia_exists
    ignore_errors: yes

  - name: Download Caskaydia
    when: Caskaydia_exists is failed
    ansible.builtin.unarchive:
      src: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/CascadiaCode.zip
      dest: "{{ lookup('env', 'HOME') }}/.fonts/"
      remote_src: yes

  - name: Install stylua Rust package
    community.general.cargo:
      name: stylua

  - name: Install python packages
    pip:
      name: "{{ item }}"
      extra_args: --upgrade
      executable: pip3
    with_items:
    - neovim-remote

  - name: Install lazygit
    shell: "go install github.com/jesseduffield/lazygit@latest"

