- hosts: localhost
  become: true
  gather_facts: yes
  vars_files:
    - ./ansible-vars.yaml

  pre_tasks:
  - name: Install update-manager-core
    apt: name=update-manager-core
    when: not update

  - name: Update apt repo and cache
    apt:
      update_cache: yes
      force_apt_get: yes
      cache_valid_time: 3600

  - name: Upgrade all packages on servers
    apt:
      upgrade: dist
      force_apt_get: yes

  - name: Add PPA repositories
    ansible.builtin.apt_repository:
      repo: "{{ item }}"
    with_items:
    - ppa:neovim-ppa/stable
    - ppa:cwchien/gradle

  - name: Install node ppa
    shell: curl -sL https://deb.nodesource.com/setup_current.x | sudo -E sh -

  - name: Install packages
    apt:
      name: "{{ item }}"
      state: latest
    with_items:
    - apt-transport-https
    - black
    - cargo
    - cpanminus
    - daemonize
    - dbus-user-session
    - default-jdk
    - dos2unix
    - fd-find
    - flake8
    - fontconfig
    - fzf
    - gcc
    - gradle
    - g++
    - jq
    - locate
    - luarocks
    - lynx
    - make
    - neovim
    - nodejs
    - python3-dev
    - python3-pip
    - ripgrep
    - ruby-full
    - shellcheck
    - silversearcher-ag
    - sqlite3
    - tmux
    - zsh
    when: not update

  - name: Install python packages
    pip:
      name: "{{ item }}"
      extra_args: --upgrade
      executable: pip3
    with_items:
    - pynvim
    - msgpack

  - name: Install NPM packages
    community.general.npm:
      name: "{{ item }}"
      version: latest
      global: yes
    with_items:
    - npm
    - neovim
    - '@fsouza/prettierd'
    - eslint_d

  - name: Install latest neovim gem
    community.general.gem:
      name: neovim
      state: latest

  - name: Install glow
    community.general.snap:
      name: "{{ item.name }}"
      classic: "{{ item.classic }}"
    when: item.install
    with_items:
    - { name: glow, classic: no, install: yes }
    - { name: powershell, classic: yes, install: "{{ install_pwsh }}" }

  - name: Install Azure CLI
    shell: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
    when: install_azcli

  - name: Get dive latest version
    shell: |
      DIVE_VERSION=$(curl -s "https://api.github.com/repos/wagoodman/dive/releases/latest" | grep -Po '"tag_name": "v\K[0-9.]+')
      curl -Lo dive.deb "https://github.com/wagoodman/dive/releases/latest/download/dive_${DIVE_VERSION}_linux_amd64.deb"
      sudo apt install -y ./dive.deb
      rm -rf dive.deb

  roles:
  - role: gantsign.golang
    vars:
    - golang_version: "{{ go_version }}"
    - golang_install_dir: "{{ go_install_dir }}"
    when: install_go
  - role: lean_delivery.java
    # vars:
      # transport: repositories
      # java_major_version: "{{ java_major_version }}"
    when: install_java or install_maven
  - role: tecris.maven
    when: install_maven

  post_tasks:
  - name: Install kubectl and kubelogin
    shell: az aks install-cli --install-location /usr/local/bin/kubectl --kubelogin-install-location /usr/local/bin/kubelogin

  - name: Remove useless packages from the cache
    apt:
      autoclean: yes

  - name: Remove dependencies that are no longer required
    apt:
      autoremove: yes

  - name: ensure fonts directory
    become: false
    file:
      path: "{{ lookup('env', 'HOME') }}/.fonts"
      state: directory

  - name: Caskaydia exists
    become: false
    shell: "ls {{ lookup('env', 'HOME') }}/.fonts/Caskaydia*Nerd*Font*Complete*"
    register: Caskaydia_exists
    ignore_errors: yes

  - name: Download Caskaydia
    become: false
    when: Caskaydia_exists is failed
    ansible.builtin.unarchive:
      src: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/CascadiaCode.zip
      dest: "{{ lookup('env', 'HOME') }}/.fonts/"
      remote_src: yes

  - name: cache fonts
    become: false
    shell: fc-cache -fv

  - name: Install zoxide
    become: false
    shell: curl -sS https://webinstall.dev/zoxide | bash

  - name: Install stylua Rust package
    become: false
    community.general.cargo:
      name: stylua

  - name: Install lazygit
    become: false
    shell: "{{ go_install_dir }}/bin/go install github.com/jesseduffield/lazygit@latest"

  - name: Install python packages
    become: false
    pip:
      name: "{{ item }}"
      extra_args: --upgrade
      executable: pip3
    with_items:
    - neovim-remote

  - name: Install NVIM config
    become: false
    shell: "mkdir -p ${HOME}/.config && rm -rf ${HOME}/.local/share/nvim/ ${HOME}/.config/nvim/ ${HOME}/.cache/nvim/ && cp -a ./nvim ${HOME}/.config/"
    when: not update

  - name: Check tmux-plugins is installed
    become: false
    stat:
      path: ${HOME}/.tmux/plugins/tpm
    register: register_name
  - name: Install tmux plugins
    become: false
    shell: "git clone https://github.com/tmux-plugins/tpm ${HOME}/.tmux/plugins/tpm"
    when: not register_name.stat.exists
  - name: Update tmux plugins
    become: false
    shell: "cd ${HOME}/.tmux/plugins/tpm && git pull"
    when: register_name.stat.exists
  - name: Update tmux config
    become: false
    shell: "cp ./shell/.tmux.conf ${HOME}/"

  - name: Customize Zshell
    become: false
    shell: |
      rm -rf $HOME/.oh-my-zsh
      sh -c "$(wget https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O -)"
      cp -a ./shell/zshcustom/* ${HOME}/.oh-my-zsh/custom/
      cp -a ./shell/bin ./shell/.*profile ./shell/.gitconfig ${HOME}/
      sed -i 's/^ZSH_THEME=.*$/ZSH_THEME="agnoster"/' ${HOME}/.zshrc
      git clone https://github.com/zsh-users/zsh-autosuggestions ${HOME}/.oh-my-zsh/custom/plugins/zsh-autosuggestions
      git clone https://github.com/zsh-users/zsh-history-substring-search ${HOME}/.oh-my-zsh/custom/plugins/zsh-history-substring-search
      git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${HOME}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
      sed -i 's/^plugins=.*$/plugins=(ag docker kubectl z zsh-autosuggestions history-substring-search zsh-syntax-highlighting)/' ${HOME}/.zshrc
      echo export PATH=\$PATH:\${HOME}/.cargo/bin >>${HOME}/.profile

  - name: Add PATH for golang
    become: false
    shell: echo export PATH=\$PATH:{{ go_install_dir }}/bin >>${HOME}/.profile
    when: install_go

  - name: Add PATH for Maven
    become: false
    shell: echo export PATH=\$PATH:/opt/apache-maven-{{ maven_version }}/bin >>${HOME}/.profile
    when: install_maven

  - name: Install Pulumi
    become: false
    shell: |
      curl -fsSL https://get.pulumi.com | sh -s""
      echo export PATH=\$PATH:\${HOME}/.pulumi/bin >>${HOME}/.profile
    when: install_pulumi
