- hosts: localhost
  become: true
  gather_facts: False
  tasks:
  - name: Install update-manager-core
    apt: name=update-manager-core
  - name: Update apt repo and cache
    apt:
      update_cache: yes
      force_apt_get: yes
      cache_valid_time: 3600
  - name: Upgrade all packages on servers
    apt:
      upgrade: dist
      force_apt_get: yes

  - name: Add Neovim stable repository from PPA and install its signing key on Ubuntu target
    ansible.builtin.apt_repository:
      repo: ppa:neovim-ppa/stable

  - name: Install packages
    apt: name={{item}}
    with_items:
      - apt-transport-https
      - black
      - cargo
      - cpanminus
      - daemonize
      - dbus-user-session
      - default-jdk
      - dos2unix
      - fd-find
      - flake8
      - fontconfig
      - fzf
      - locate
      - luarocks
      - lynx
      - neovim
      - nodejs
      - python3-dev
      - python3-pip
      - ripgrep
      - ruby-full
      - shellcheck
      - silversearcher-ag
      - sqlite3
      - tmux
      - zsh

  - name: Install python package
  pip:
    name:
      - pynvim
      - msgpack
    extra_args: --upgrade
    executable: pip3
