- hosts: localhost
  become: true
  gather_facts: yes
  vars_files:
    - ./ansible-vars.yaml
  tasks:
  - name: ensure fonts directory
    file:
      path: "{{ lookup('env', 'HOME') }}/.fonts"
      state: directory

  - name: Caskaydia exists
    shell: "ls {{ lookup('env', 'HOME') }}/.fonts/Caskaydia*Nerd*Font*Complete*"
    register: Caskaydia_exists
    ignore_errors: yes

  - name: Download Caskaydia
    when: Caskaydia_exists is failed
    ansible.builtin.unarchive:
      src: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/CascadiaCode.zip
      dest: "{{ lookup('env', 'HOME') }}/.fonts/"
      remote_src: yes

  - name: cache fonts
    shell: "fc-cache -fv"

  - name: Install stylua Rust package
    community.general.cargo:
      name: stylua

  - name: Install python packages
    pip:
      name: "{{ item }}"
      extra_args: --upgrade
      executable: pip3
    with_items:
    - neovim-remote

  - name: Install NVIM config
    shell: "mkdir -p ${HOME}/.config && rm -rf ${HOME}/.local/share/nvim/ ${HOME}/.config/nvim/ ${HOME}/.cache/nvim/ && cp -a ./nvim ${HOME}/.config/"

  - name: Install tmux consif and plusing
    shell: "git clone https://github.com/tmux-plugins/tpm ${HOME}/.tmux/plugins/tpm && cp ./shell/.tmux.conf ${HOME}/"

  - name: Install Pulumi
    shell: "curl -fsSL https://get.pulumi.com | sh -s"
    when: install_pulumi

  - name: Customize Zshell
    shell: |
      sh -c "$(wget https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O -)"
      cp -a ./shell/zshcustom/* ${HOME}/.oh-my-zsh/custom/
      cp ./shell/.*profile ${HOME}/
      sed -i 's/^ZSH_THEME=.*$/ZSH_THEME="agnoster"/' ${HOME}/.zshrc
      git clone https://github.com/zsh-users/zsh-autosuggestions ${HOME}/.oh-my-zsh/custom/plugins/zsh-autosuggestions
      git clone https://github.com/zsh-users/zsh-history-substring-search ${HOME}/.oh-my-zsh/custom/plugins/zsh-history-substring-search
      git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${HOME}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
      sed -i 's/^plugins=.*$/plugins=(ag docker kubectl z zsh-autosuggestions history-substring-search zsh-syntax-highlighting)/' ${HOME}/.zshrc
