- hosts: localhost
  become: true
  gather_facts: yes
  vars:
    install_azcli: true
    install_pwsh: true
    install_go: true
    install_java: true
    java_major_version: 11
    install_gradle: true
    gradle_version: 7.4.2
    install_maven: true
    golang_version: 1.18

  pre_tasks:
  # - name: Install roles
  #   command: ansible-galaxy role install {{ item }}
  #   with_items:
  #   - gantsign.golang
  #   - shelleg.gradle
  #   - lean_delivery.java

  - name: Install update-manager-core
    apt: name=update-manager-core

  - name: Update apt repo and cache
    apt:
      update_cache: yes
      force_apt_get: yes
      cache_valid_time: 3600

  - name: Upgrade all packages on servers
    apt:
      upgrade: dist
      force_apt_get: yes

  - name: Add PPA repositories
    ansible.builtin.apt_repository:
      repo: "{{ item }}"
    with_items:
    - ppa:neovim-ppa/stable
    - ppa:cwchien/gradle

  - name: Install node ppa
    shell: curl -sL https://deb.nodesource.com/setup_current.x | sudo -E sh -

  - name: Install packages
    apt: name={{ item }}
    with_items:
    - apt-transport-https
    - black
    - cargo
    - cpanminus
    - daemonize
    - dbus-user-session
    - default-jdk
    - dos2unix
    - fd-find
    - flake8
    - fontconfig
    - fzf
    - gcc
    - g++
    - locate
    - luarocks
    - lynx
    - make
    - neovim
    - nodejs
    - python3-dev
    - python3-pip
    - ripgrep
    - ruby-full
    - shellcheck
    - silversearcher-ag
    - sqlite3
    - tmux
    - zsh

  - name: Install python packages
    pip:
      name: "{{ item }}"
      extra_args: --upgrade
      executable: pip3
    with_items:
    - pynvim
    - msgpack

  - name: Install NPM packages
    community.general.npm:
      name: "{{ item }}"
      version: latest
      global: yes
    with_items:
    - npm
    - neovim
    - '@fsouza/prettierd'
    - eslint_d

  - name: Install latest neovim gem
    community.general.gem:
      name: neovim
      state: latest

  - name: Install glow
    community.general.snap:
      name: "{{ item.name }}"
      classic: "{{ item.classic }}"
    with_items:
    - { name: glow, classic: no }
    - { name: powershell, classic: yes }

  - name: Install Azure CLI
    shell: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
    when: install_azcli

  roles:
  - role: gantsign.golang
    when: install_go
    vars:
    # - golang_version: {{ golang_version }}
    - golang_install_dir: /opt/go
  - role: lean_delivery.java
    transport: repositories
    java_major_version: "{{ java_major_version }}"
    when: install_java or install_gradle or install_maven
  - role: shelleg.gradle
    vars:
    - gradle_version: "{{ gradle_version }}"
    when: install_gradle

  post_tasks:
  - name: Install kubectl and kubelogin
    shell: az aks install-cli --install-location /usr/local/bin/kubectl --kubelogin-install-location /usr/local/bin/kubelogin

  - name: Remove useless packages from the cache
    apt:
      autoclean: yes

  - name: Remove dependencies that are no longer required
    apt:
      autoremove: yes
